- hosts: localhost
  vars:
    main_user: "uta8a"
  tasks:
    - name: update and upgrade
      apt:
        update_cache: yes
        upgrade: 'yes'
      become: yes
    - name: install via apt
      apt:
        pkg:
          - cmake
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - binutils
          - build-essential
          - cmake
          - curl
          - default-jdk
          - docker-compose
          - containerd
          - docker.io
          - emacs
          - fcitx-mozc
          - ffmpeg
          - file
          - gcc
          - gdb
          - ghex
          - git
          - gnome-getting-started-docs-ja
          - gnome-user-docs-ja
          - htop
          - inetutils-traceroute
          - libpq-dev
          - libssl-dev
          - ltrace
          - nasm
          - netcat
          - python-is-python3
          - python3
          - python3-dev
          - python3-pip
          - python3-venv
          - qemu
          - qemu-system-x86
          - radare2
          - ssh
          - strace
          - tmux
          - tree
          - ubuntu-restricted-extras
          - vim
          - wget
      become: yes
    - name: checksec
      include_tasks: tasks/checksec.yml
    - name: rp++
      include_tasks: tasks/rp.yml
    - name: Rust
      shell:
        cmd: curl -sSf https://sh.rustup.rs | sh -s -- -y
        creates: ~/.cargo
    - name: aracritty
      shell:
        cmd: cargo install alacritty
    - name: bootimage
      shell:
        cmd: cargo install bootimage
    # - name: cargo-bootimage
    #   shell:
    #     cmd: cargo install cargo-bootimage
    # - name: cargo-add
    #   shell:
    #     cmd: cargo install cargo-add
    # - name: cargo-rm
    #   shell:
    #     cmd: cargo install cargo-rm
    # - name: cargo-upgrade
    #   shell:
    #     cmd: cargo install cargo-upgrade
    # - name: cargo-license
    #   shell:
    #     cmd: cargo install cargo-license
    # - name: cargo-outdated
    #   shell:
    #     cmd: cargo install cargo-outdated
    # - name: cargo-install-update
    #   shell:
    #     cmd: cargo install cargo-install-update
    # - name: cargo-install-update-config
    #   shell:
    #     cmd: cargo install cargo-install-update-config
    # - name: diesel
    #   shell:
    #     cmd: cargo install diesel
    # - name: hexyl
    #   shell:
    #     cmd: cargo install hexyl
    - name: ripgrep
      shell:
        cmd: cargo install ripgrep
    - name: silicon
      shell:
        cmd: cargo install silicon 
    - name: mkdir ~/tools/vscode
      file:
        path: ~/tools/vscode
        state: directory
        mode: '0755'
    - name: VSCode download
      shell:
        cmd: curl -L https://go.microsoft.com/fwlink/?LinkID=760868 -o ~/tools/vscode/vscode.deb
        creates: ~/tools/vscode/vscode.deb
    - name: VSCode install
      apt:
        deb: "/home/{{ main_user }}/tools/vscode/vscode.deb"
      become: yes
