- name: mkdir ~/tools/checksec
  file:
    path: ~/tools/checksec
    state: directory
    mode: '0755'
- name: git clone repo
  git:
    repo: https://github.com/slimm609/checksec.sh.git
    dest: ~/tools/checksec
- name: chmod
  file: 
    path: ~/tools/checksec/checksec
    mode: u+x
- name: cp
  copy:
    src: "/home/{{ main_user }}/tools/checksec/checksec"
    dest: /usr/local/bin/checksec
    remote_src: yes
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0777'
  become: yes
